spring.application.name=microservico-usuarios
server.port=8082

# URL de Conexao
spring.datasource.url=${AZURE_SQL_URL}

# Credenciais
spring.datasource.username=${AZURE_SQL_USER}
spring.datasource.password=${AZURE_SQL_PASSWORD}

# Configuracoes do Hibernate (A magica que cria as tabelas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html