spring.application.name=microservico-usuarios
server.port=8082

# URL de Conexao
spring.datasource.url=jdbc:sqlserver://NOME-DO-SERVIDOR.database.windows.net:1433;database=NOME-DO-BANCO;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

# Credenciais
spring.datasource.username=SEU_USUARIO_AQUI
spring.datasource.password=SUA_SENHA_AQUI

# Configura??es do Hibernate (A m?gica que cria as tabelas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html